# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-docstring-first
      - id: debug-statements
      - id: check-yaml
      - id: check-ast
      - id: flake8
  - repo: https://github.com/ambv/black
    rev: 19.10b0
    hooks:
      - id: black
        args: [--line-length=79]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.770
    hooks:
      - id: mypy
  - repo: https://github.com/pycqa/isort
    rev: 5.7.0
    hooks:
      - id: isort
        files: \.py$
