name: stairway-backend
channels:
  - defaults
dependencies:
  - jupyter=1.0.0
  - pandas=0.24.1
  - python=3.7.2
  - flask=1.0.2
  - pytest=6.1.1
  - basemap=1.2.0
  - matplotlib=3.2.2
  - imageio=2.9.0
  - pip:
    - google-cloud-firestore==0.31.0
    - flask-restful==0.3.7
    - Flask-Cors==3.0.9
    - Pillow==8.0.1
