runtime: python37

handlers:
- url: /.*
  script: auto

instance_class: F1
automatic_scaling:
  min_pending_latency: 2.5s
  target_cpu_utilization: 0.8
  target_throughput_utilization: 0.8
  max_concurrent_requests: 50

#env_variables:
#  STAIRWAY_FIRESTORE_KEY: ${STAIRWAY_FIRESTORE_KEY}
