runtime: python37
#api_version: 1
#threadsafe: true

handlers:
#- url: /static
#  static_dir: static
- url: /.*
  script: auto

#libraries:
#  - name: ssl
#    version: latest

#env_variables:
#  STAIRWAY_FIRESTORE_KEY: ${STAIRWAY_FIRESTORE_KEY}
