runtime: python37

handlers:
- url: /.*
  script: auto

#instance_class: F2
#automatic_scaling:
#  min_idle_instances: 1
#  target_cpu_utilization: 0.8
#  max_concurrent_requests: 50
#  max_pending_latency: 1000ms

#env_variables:
#  STAIRWAY_FIRESTORE_KEY: ${STAIRWAY_FIRESTORE_KEY}
